// Code generated by protoc-gen-go.
// source: ipc/ipc.proto
// DO NOT EDIT!

/*
Package ipc is a generated protocol buffer package.

It is generated from these files:
	ipc/ipc.proto

It has these top-level messages:
	Header
*/
package ipc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// reserve first 20 for type
type Header struct {
	Type  uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Flags uint32 `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
	Body  []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Header) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Header) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "ipc.Header")
}

func init() { proto.RegisterFile("ipc/ipc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2c, 0x48, 0xd6,
	0xcf, 0x2c, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2c, 0x48, 0x56, 0x72,
	0xe3, 0x62, 0xf3, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x12, 0x12, 0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0xd3, 0x72, 0x12,
	0xd3, 0x8b, 0x25, 0x98, 0xc0, 0x82, 0x10, 0x0e, 0x48, 0x65, 0x52, 0x7e, 0x4a, 0xa5, 0x04, 0xb3,
	0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0x9d, 0xc4, 0x06, 0x36, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0xe8, 0xd2, 0xd8, 0x64, 0x00, 0x00, 0x00,
}
